### ISSUE TITLE
async def _get_region blocks forever

### ISSUE THREAD

**Issue by johannesloibl** [hlf20010508/miniopy-async#16]
# Bug Report

## Describe the bug
put_object is running into a timeout, because of an indentation error in 
api.py:473:
```
async with aiohttp.ClientSession() as session:
	response = await self._url_open(
		"GET",
		"us-east-1",
		bucket_name=bucket_name,
		query_params={"location": ""},
		session=session,
	)

element = ET.fromstring(await response.text())
```
`await response` is outside the context manager and the session already got closed, leading to a timeout after some minutes.
Indenting the line fixes the problem.
PR incoming.

**Comment by hlf20010508** [comment]
Merged
