### ISSUE TITLE
session argument ignored in method _execute

### ISSUE THREAD

**Issue by erny** [hlf20010508/miniopy-async#18]
# Bug Report

## Describe the bug
session argument ignored
* https://github.com/hlf20010508/miniopy-async/blob/f1b8912869b5ac0581224c688c3943aba4d5073a/miniopy_async/api.py#L412

## Expected behavior
Don't ignore session argument

**Comment by hlf20010508** [comment]
Thank you for your issue.

**Comment by hlf20010508** [comment]
New version published.
