### ISSUE TITLE
Can't import aiostream

### ISSUE THREAD

**Issue by erny** [hlf20010508/miniopy-async#19]
# Bug Report

## Describe the bug
aiostream is not included in the dependencies

## To Reproduce

    # Inside new virtualenv
    python setup.py install
    python tests.py

## Expected behavior
tests should be run

## Screenshots or Outputs

    Traceback (most recent call last):
      File "/home/erevilla/svn/miniopy-async/tests.py", line 19, in <module>
        from aiostream.stream import list as alist
    ModuleNotFoundError: No module named 'aiostream'

## Desktop:
 - OS: Ubuntu Linux, 20.04

**Comment by hlf20010508** [comment]
But `aiostream` is only used in tests.py, it's not a dependency of `miniopy-async`.

**Comment by hlf20010508** [comment]
Yeah actually `aiostream` is not needed.

I'll change the code of `tests.select_object_content`
```py
for data in await alist(result.stream())
```

to

```py
async for data in result.stream()
```
