### ISSUE TITLE
[SSLCertVerificationError]: How do I ignore checking a self-signed certificate

### ISSUE THREAD

**Issue by Gu-f** [hlf20010508/miniopy-async#24]
I am using https but I am using a self-signed certificate and I need to turn off ssl certificate verification.
What should I do?

**Comment by hlf20010508** [comment]
This repo is based on a very old version of `minio-py` which doesn't support param `cert_check`.
I'm now trying to support this param.

**Comment by hlf20010508** [comment]
Please use `pip install git+https://github.com/hlf20010508/miniopy-async.git` to have a try.

```py
client = Minio(
    "xxxx.com",
    access_key="xxxx",
    secret_key="xxxx",
    secure=True,
    cert_check=False,
)
```

**Comment by Gu-f** [comment]
working well. thanks!  
It is hoped that the release-version will be supported in the future.

**Comment by hlf20010508** [comment]
New version published.
