### ISSUE TITLE
Consider distributing on conda-forge

### ISSUE THREAD

**Issue by matthewfeickert** [hlf20010508/miniopy-async#25]
# Feature Request

:wave: Hi. Would you be open to distributing `miniopy-async` on conda-forge as well? 

It looks like it would be pretty straightforward to do given that `grayskull` (which can build the recipe for you) passes without any missing dependencies.

```console
$ grayskull pypi --list-missing-deps --strict-conda-forge miniopy-async



#### Initializing recipe for miniopy-async (pypi) ####

Recovering metadata from pypi...
Starting the download of the sdist package miniopy-async
miniopy-async 100% Time:  0:00:00   1.8 MiB/s|############################################################################################################################################################|
Checking for pyproject.toml
pyproject.toml not found.
Recovering information from setup.py
Executing injected distutils...
ERROR: Could not find an activated virtualenv (required).
ERROR:It was not possible to install setuptools.
Command: pip install setuptools --target=/tmp/pip-dir-0i63b_4n.
Error: Command '['/home/feickert/.pixi/envs/grayskull/bin/python3.12', '-m', 'pip', 'install', 'setuptools', '--target=/tmp/pip-dir-0i63b_4n']' returned non-zero exit status 3.
Recovering metadata from setup.cfg
Checking >> urllib3 100% |#########################################################################################################################################################|[Elapsed Time: 0:00:02]
Recovering license info from spdx.org ...
INFO:Best match for license Apache2.0 was Apache-2.0.
Best matches: ['Apache-2.0']
License type: Apache-2.0
License file: ['LICENSE']
Build requirements:
  <none>
Host requirements:
  - python >=3.7
  - pip
Run requirements:
  - python >=3.7
  - certifi
  - aiofile
  - aiohttp
  - urllib3

RED: Missing packages
GREEN: Packages available on conda-forge
All dependencies are already on conda-forge.

Maintainers:
   - hlf20010508

#### Recipe generated on /tmp for miniopy-async ####


```

I would be willing to help walk you through adding a package to conda-forge if this is the first time you've done this.

## Is your feature request related to a problem? Please describe.
No, it is motivated by https://github.com/ssl-hep/ServiceX_frontend/issues/352.

## Describe the solution you'd like

Add `miniopy-async` to https://github.com/conda-forge/staged-recipes through making a PR with the recipe generated by `grayskull`.

## Describe alternatives you've considered
None.

**Comment by hlf20010508** [comment]
I've generated a `meta.yaml` through `grayskull`.
What should I do next?

**Comment by matthewfeickert** [comment]
> I've generated a `meta.yaml` through `grayskull`.

Great!

> What should I do next?

1. For https://github.com/conda-forge/staged-recipes/
2. Make a new branch on your fork (e.g. `feat/add-miniopy-async`)
3. Copy the `meta.yml` you generated to `recipes/miniopy-async/meta.yml`.
4. Add and commit the recipe.
4. Do some checks that things look good (e.g. you could run [`build-locally.py`](https://github.com/conda-forge/staged-recipes/blob/73fe1c7dd4c27b801d18e781f0f0ae38701a6187/build-locally.py) to test)
5. Push your changes to your fork and open a PR to https://github.com/conda-forge/staged-recipes
6. Wait for the CI to run successfully and if there are any failures from the workflow or the linter either debug them or tag me to ask for help.
7. Once all the CI has run successfully comment `@conda-forge/help-python, ready for review` in the PR to get a reviewer to come review and approve your recipe PR.

If you'd like some recent examples of what this looks like check out https://github.com/conda-forge/staged-recipes/pull/25789.

**Comment by hlf20010508** [comment]
I've opened a [PR](https://github.com/conda-forge/staged-recipes/pull/25848) there.

**Comment by matthewfeickert** [comment]
Okay, now that https://github.com/conda-forge/staged-recipes/pull/25848 has been merged, conda-forge generated a `miniopy-async` feedstock at https://github.com/conda-forge/miniopy-async-feedstock which will autogenerate a PR to update itself everytime there is a PyPI release.

Within a few hours the conda-forge index will update and 

```
micromamba search miniopy-async
```

should show that `miniopy-async` is available for use on conda-forge. :+1:

**Comment by hlf20010508** [comment]
@matthewfeickert Hi, is there a way to allow conda-forge auto merge the pull request for new version?

**Comment by matthewfeickert** [comment]
@hlf20010508 I'm in transit at the moment, so I'll quickly reply to just say yes. Instructions here: https://conda-forge.org/docs/maintainer/infrastructure/#conda-forge-admin-please-add-bot-automerge

**Comment by hlf20010508** [comment]
Thanks for your help.
