### ISSUE TITLE
update to the latest version of official minio python driver (minio-py)

### ISSUE THREAD

**Issue by qu4dve** [hlf20010508/miniopy-async#6]
hi, thanks for this package. 
do you have any plan to support this repository?
it this rep always be updated with the latest minio python driver (minio-py) ?

**Comment by hlf20010508** [comment]
> hi, thanks for this package.
> do you have any plan to support this repository?
> it this rep always be updated with the latest minio python driver (minio-py) ?

Hi, is there any feature that you need from the newest minio-py but not supported in miniopy-async?
I think it is difficult for me to update this repository for now. I'm quite busy this year.

**Comment by qu4dve** [comment]
no, there is not any specific feature rn.
i wanted to use this package and i was just wondering are you gonna update this(for long term) or not ?
if the official driver introduces new important feature, do you update this rep(long term)?

**Comment by hlf20010508** [comment]
> no, there is not any specific feature rn.
> 
> i wanted to use this package and i was just wondering are you gonna update this(for long term) or not ?
> 
> if the official driver introduces new important feature, do you update this rep(long term)?
> 
> 
> 
> 
> 
> 

sorry i won't do it for now. I'm a senior student. I don't have much time to do so this year. but maybe two years later i'll have time.
